apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: healthchecks-sync
rules:
- apiGroups:
  - ""
  - batch
  attributeRestrictions: null
  resources:
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - project.openshift.io
  attributeRestrictions: null
  resources:
  - projects
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list

